# Generated by Django 4.2.7 on 2023-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_t', models.CharField(max_length=250)),
                ('img_t', models.ImageField(upload_to='pics')),
                ('desc_t', models.TextField()),
            ],
        ),
    ]
